INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Tiramisu', 'Ladyfingers, espresso, mascarpone, eggs, sugar, cocoa powder', 240, 'Start by mixing egg yolks with sugar until pale and thick. Beat in mascarpone cheese until smooth. In a separate bowl, whip egg whites to soft peaks and fold into the mascarpone mixture gently to keep it airy. Dip ladyfingers briefly in espresso and lay them in a dish. Cover with a layer of the mascarpone mixture. Repeat layers until ingredients are used up, finishing with mascarpone. Chill for at least 4 hours. Dust with cocoa powder before serving. Each step is crucial for achieving the classic tiramisu texture and flavor.', 4, 1, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/Tiramisu.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Cheesecake', 'Cream cheese, sugar, eggs, crust (graham crackers, butter, sugar)', 120, 'For the crust, combine crushed graham crackers, melted butter, and sugar, press into a pan, and bake until golden. Beat cream cheese until smooth, add sugar, then eggs one at a time. Pour the mixture over the crust and bake in a water bath to prevent cracking. Cool slowly in the oven, then chill overnight. The gradual cooling helps prevent surface cracks and ensures a smooth texture.', 4, 2, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/cheesecake.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Crème Brûlée', 'Heavy cream, vanilla bean, egg yolks, sugar', 60, 'Warm cream with vanilla bean to infuse. Whisk yolks with sugar until thick. Slowly blend in the cream. Strain into ramekins. Bake in a water bath at low temp until set but slightly wobbly. Cool, then chill. Sprinkle with sugar and torch to caramelize just before serving. The key is the contrast between the brittle caramelized top and the smooth, creamy custard.', 4, 3, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/crmebrle.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Macarons', 'Almond flour, egg whites, sugar, food coloring', 90, 'Shift almond flour and powdered sugar together. Whip egg whites to soft peaks, gradually add sugar until stiff peaks form. Fold in the almond mixture and coloring gently. Pipe onto lined baking sheets. Let stand to form a skin. Bake until set but not browned. Fill with ganache or buttercream. Precise measurements and folding technique are crucial for the perfect texture and feet.', 4, 4, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/macarons.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Pavlova', 'Egg whites, sugar, vinegar, cornflour, heavy cream, fruit', 180, 'Whip egg whites to soft peaks, gradually add sugar until glossy. Fold in vinegar and cornflour. Shape on a lined tray and bake at low heat until crisp outside and soft inside. Cool in the oven with the door slightly ajar. Top with whipped cream and fresh fruit. The key to Pavlova is the marshmallow-like center contrasted with a crisp crust, achieved by precise baking and cooling.', 4, 5, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/pavlova.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Chocolate Lava Cake', 'Dark chocolate, butter, eggs, sugar, flour', 30, 'Melt chocolate and butter together. Whisk eggs and sugar, then fold into the chocolate mixture along with flour. Pour into buttered ramekins. Bake just until the edges are set but the center is still liquid. Serve immediately to enjoy the molten center. The timing is critical for the lava effect, requiring precise baking.', 4, 6, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/chocolatelavacake.jpg?raw=true');


INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Baklava', 'Phyllo dough, nuts, butter, sugar, honey', 90, 'Layer phyllo sheets, brushing each with melted butter, and sprinkle chopped nuts between layers. Cut into diamonds before baking. Bake until golden and crisp. Meanwhile, cook a syrup of sugar, honey, and water. Pour the hot syrup over the baked baklava. Let it soak in for hours before serving. The key to good baklava is the crispy layers soaked in sweet, flavorful syrup.', 4, 7, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/baklava.jpg?raw=true');


INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Eggs Benedict', '2 English muffins, 4 eggs, 4 slices of Canadian bacon, Hollandaise sauce', 25, 'Eggs Benedict is a classic breakfast dish that consists of toasted English muffins topped with Canadian bacon, poached eggs, and creamy Hollandaise sauce. To prepare, first, toast the English muffins until they are golden brown. While the muffins are toasting, poach the eggs in gently simmering water until the whites are set but the yolks are still runny. In a separate pan, warm the Canadian bacon slices until they are heated through. Once everything is ready, assemble the dish by placing a slice of Canadian bacon on each half of the English muffins, followed by a poached egg. Finally, generously drizzle Hollandaise sauce over the top. Serve immediately, garnished with chopped parsley if desired.', 1, 8, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/eggsBenedict.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('French Toast', '4 slices of bread, 2 eggs, 1/4 cup milk, 1 teaspoon vanilla extract, butter, maple syrup (optional)', 20, 'French Toast is a delicious and comforting breakfast treat that is easy to make. To prepare, whisk together eggs, milk, and vanilla extract in a shallow dish. Dip each slice of bread into the egg mixture, ensuring they are evenly coated on both sides. Heat a skillet or griddle over medium heat and melt butter. Cook the soaked bread slices until they are golden brown and crispy on each side. Serve hot with a drizzle of maple syrup for sweetness, if desired.', 1, 9, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/Frenchtoast.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Oatmeal', '1/2 cup rolled oats, 1 cup water, pinch of salt, toppings of your choice (e.g., fruits, nuts, honey)', 15, 'Oatmeal is a hearty and nutritious breakfast option that is quick to prepare. To make oatmeal, bring water and a pinch of salt to a boil in a small saucepan. Stir in the rolled oats and reduce the heat to low. Simmer the oats, stirring occasionally, until they are tender and creamy, about 5 minutes. Remove the oatmeal from the heat and let it sit for a minute to thicken. Serve hot, topped with your favorite toppings such as fresh fruits, nuts, or a drizzle of honey.', 1, 1, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/oatmeal.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Pancakes', '1 cup all-purpose flour, 2 tablespoons sugar, 1 teaspoon baking powder, 1/2 teaspoon baking soda, 1/4 teaspoon salt, 1 cup buttermilk, 1 egg, 2 tablespoons unsalted butter (melted), butter or oil for cooking', 30, 'Pancakes are a classic breakfast favorite that is sure to please everyone. To make pancakes, start by whisking together the dry ingredients in a large bowl: flour, sugar, baking powder, baking soda, and salt. In a separate bowl, whisk together the wet ingredients: buttermilk, egg, and melted butter. Pour the wet ingredients into the dry ingredients and stir until just combined (some lumps are okay). Heat a skillet or griddle over medium heat and grease with butter or oil. Pour the pancake batter onto the skillet to form pancakes of your desired size. Cook until bubbles form on the surface, then flip and cook until golden brown on both sides. Serve hot with butter and maple syrup.', 1, 2, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/pancakes.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Avocado Toast', '2 slices of bread, 1 ripe avocado, salt, pepper, red pepper flakes, lemon juice ', 10, 'Avocado Toast is a simple yet satisfying breakfast or snack option. Start by toasting the bread until it is golden and crispy. While the bread is toasting, mash the ripe avocado in a bowl until smooth and creamy. Season the mashed avocado with salt, pepper, and red pepper flakes for a kick of heat if desired. Once the bread is toasted, spread the mashed avocado generously over each slice. Finish with a squeeze of fresh lemon juice for brightness. Serve immediately for a delicious and nutritious meal.', 1, 3, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/avocado%20toast.jpg?raw=true');
 
INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Shakshuka', '1 tablespoon olive oil, 1 onion (chopped), 1 bell pepper (chopped), 2 cloves garlic (minced), 1 can (14 oz) diced tomatoes, 1 teaspoon paprika, 1/2 teaspoon cumin, 1/4 teaspoon cayenne pepper, salt, pepper, 4-6 eggs, feta cheese (optional), fresh parsley (chopped)', 35, 'Shakshuka is a flavorful and hearty dish that is perfect for breakfast or brunch. To make Shakshuka, start by heating olive oil in a large skillet over medium heat. Add chopped onion and bell pepper, and cook until they are softened and starting to caramelize, about 5 minutes. Add minced garlic and cook for another minute until fragrant. Stir in diced tomatoes, paprika, cumin, cayenne pepper, salt, and pepper, and simmer for 10-15 minutes until the sauce has thickened slightly. Make small wells in the sauce and crack an egg into each well. Cover the skillet and cook until the eggs are set to your liking, about 5-7 minutes for runny yolks. Sprinkle crumbled feta cheese over the top for extra flavor, and garnish with chopped parsley. Serve hot with crusty bread for dipping.', 1, 4, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/shakshuka.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Bruschetta', '4 slices of baguette, 2 ripe tomatoes, 2 cloves of garlic, fresh basil leaves, extra virgin olive oil, balsamic vinegar, salt, pepper', 15, 'Bruschetta is a classic Italian appetizer that is quick and easy to make. Start by slicing the baguette into thick slices and toasting them until golden brown. Meanwhile, dice the tomatoes and finely chop the garlic cloves. In a bowl, mix the diced tomatoes, chopped garlic, torn basil leaves, a drizzle of extra virgin olive oil, and balsamic vinegar. Season with salt and pepper to taste. Once the baguette slices are toasted, top each one with the tomato mixture. Serve immediately as a delicious appetizer or snack.', 3, 5, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/bruschetta.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Caprese Salad', '2 ripe tomatoes, 1 ball of fresh mozzarella cheese, fresh basil leaves, extra virgin olive oil, balsamic glaze, salt, pepper', 10, 'Caprese Salad is a simple and refreshing Italian salad that showcases the flavors of ripe tomatoes, creamy mozzarella cheese, and fresh basil. Start by slicing the tomatoes and mozzarella cheese into thick slices. Arrange them alternately on a serving platter, overlapping slightly. Tuck fresh basil leaves in between the tomato and mozzarella slices. Drizzle with extra virgin olive oil and balsamic glaze. Season with salt and pepper to taste. Serve immediately as a light and flavorful appetizer or side dish.', 3, 6, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/Caprese%20salad.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Spring Rolls', 'Rice paper wrappers, vermicelli noodles, lettuce leaves, carrots (julienned), cucumber (julienned), fresh mint leaves, cooked shrimp (peeled and deveined), hoisin sauce, peanut sauce (optional)', 30, 'Spring Rolls are a popular Vietnamese appetizer that is light, fresh, and bursting with flavor. Start by soaking the rice paper wrappers in warm water until they become pliable. Lay a softened wrapper flat on a clean work surface. Place a lettuce leaf on the bottom third of the wrapper, followed by a small handful of vermicelli noodles, julienned carrots, cucumber, fresh mint leaves, and a couple of cooked shrimp. Fold the bottom of the wrapper over the filling, then fold in the sides, and roll tightly to seal. Repeat with the remaining wrappers and filling ingredients. Serve the spring rolls with hoisin sauce and peanut sauce for dipping, if desired.', 3, 7, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/springrolls.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Ceviche', 'Fresh white fish fillets (such as sea bass or halibut), limes, red onion (thinly sliced), cherry tomatoes (halved), cucumber (diced), cilantro (chopped), jalapeno pepper (seeded and minced), salt, pepper', 25, 'Ceviche is a popular Latin American dish made with raw fish cured in citrus juices, typically lime or lemon. Start by cutting the fish fillets into bite-sized pieces and placing them in a shallow dish. Squeeze fresh lime juice over the fish until it is completely covered. Add thinly sliced red onion, halved cherry tomatoes, diced cucumber, chopped cilantro, and minced jalapeno pepper to the dish. Season with salt and pepper to taste. Cover and refrigerate for at least 20 minutes to allow the flavors to meld and the fish to cook in the acidic lime juice. Serve the ceviche chilled as a refreshing appetizer or light main course.', 3, 8, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/ceviche.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Stuffed Mushrooms', 'Large mushrooms (such as cremini or portobello), cream cheese, garlic (minced), fresh parsley (chopped), breadcrumbs, grated Parmesan cheese, salt, pepper, olive oil', 35, 'Stuffed Mushrooms are a delicious appetizer that is perfect for entertaining. Start by removing the stems from the mushrooms and gently scraping out the gills to create a hollow cavity. In a bowl, mix together cream cheese, minced garlic, chopped parsley, breadcrumbs, and grated Parmesan cheese until well combined. Season with salt and pepper to taste. Spoon the cream cheese mixture into the mushroom caps, mounding it slightly. Drizzle olive oil over the stuffed mushrooms and bake in a preheated oven until the mushrooms are tender and the filling is golden brown and bubbly. Serve the stuffed mushrooms hot as a savory appetizer that is sure to impress your guests.', 3, 9, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/stuffedmushroom.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Hummus with Pita Bread', 'Chickpeas, tahini, garlic (minced), lemon juice, olive oil, ground cumin, salt, pepper, pita bread', 20, 'Hummus with Pita Bread is a classic Middle Eastern snack that is creamy, flavorful, and perfect for dipping. Start by rinsing and draining the chickpeas. In a food processor, combine the chickpeas, tahini, minced garlic, lemon juice, olive oil, ground cumin, salt, and pepper. Blend until smooth and creamy, adding a splash of water if needed to achieve the desired consistency. Toast the pita bread in a toaster or oven until warm and slightly crispy. Serve the hummus alongside the warm pita bread for dipping. Garnish with a drizzle of olive oil and a sprinkle of paprika, if desired.', 3, 1, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/hummus.jpg?raw=true');

INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Caesar Salad', 'Romaine lettuce, Caesar dressing, Parmesan cheese, croutons, lemon juice, Worcestershire sauce, Dijon mustard, garlic (minced), anchovy fillets (optional), olive oil, salt, pepper', 15, 'Caesar Salad is a classic dish that is crisp, refreshing, and bursting with flavor. Start by tearing the Romaine lettuce into bite-sized pieces and placing them in a large bowl. In a separate bowl, whisk together Caesar dressing, lemon juice, Worcestershire sauce, Dijon mustard, minced garlic, and anchovy fillets (if using). Slowly drizzle in olive oil while whisking continuously until the dressing is emulsified. Season with salt and pepper to taste. Add the dressing to the lettuce and toss until evenly coated. Top with shaved Parmesan cheese and croutons. Serve immediately as a delicious appetizer or side dish.', 2, 2, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/Caesar%20salad.jpg?raw=true');
  
INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Quiche Lorraine', 'Pie crust, bacon, Gruyere cheese, eggs, heavy cream, milk, salt, pepper, nutmeg', 50, 'Quiche Lorraine is a savory French tart filled with bacon, cheese, and custard. Start by preheating the oven and blind baking the pie crust until lightly golden. Meanwhile, cook the bacon until crisp and chop it into small pieces. Sprinkle the cooked bacon and shredded Gruyere cheese evenly over the bottom of the partially baked pie crust. In a bowl, whisk together eggs, heavy cream, milk, salt, pepper, and a pinch of nutmeg until well combined. Pour the egg mixture over the bacon and cheese in the pie crust. Bake the quiche until the filling is set and the top is golden brown. Let it cool slightly before slicing and serving.', 2, 3, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/QuicheLorraine.jpg?raw=true');
 
INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Chicken Caesar Wrap', 'Grilled chicken breast, Romaine lettuce, Caesar dressing, Parmesan cheese, flour tortillas', 20, 'Chicken Caesar Wrap is a tasty and satisfying lunch option that is quick and easy to make. Start by slicing the grilled chicken breast into thin strips. Lay a flour tortilla flat on a clean work surface. Place a few Romaine lettuce leaves in the center of the tortilla, followed by the sliced grilled chicken. Drizzle Caesar dressing over the chicken and sprinkle with shaved Parmesan cheese. Fold in the sides of the tortilla and roll tightly to form a wrap. Slice the wrap in half diagonally and serve immediately.', 2, 4, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/Chicken%20Caesar%20Wrap.jpg?raw=true');
  
INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Pho', 'Beef or chicken broth, rice noodles, thinly sliced beef or chicken, bean sprouts, fresh herbs (such as cilantro, Thai basil, and mint), lime wedges, hoisin sauce, sriracha sauce, thinly sliced onion, scallions, jalapeno peppers', 60, 'Pho is a Vietnamese noodle soup that iss aromatic, flavorful, and comforting. Start by bringing the broth to a simmer in a large pot. Meanwhile, prepare the rice noodles according to the package instructions. Divide the cooked noodles among serving bowls and top with thinly sliced beef or chicken. Ladle the hot broth over the noodles and meat, ensuring they are submerged. Serve the pho with bean sprouts, fresh herbs, lime wedges, hoisin sauce, sriracha sauce, thinly sliced onion, scallions, and jalapeno peppers on the side. Allow diners to customize their bowls with their preferred toppings.', 2, 5, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/Pho.jpg?raw=true');
  
INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Grilled Cheese Sandwich', 'Bread slices, cheese slices (such as cheddar, Swiss, or American), butter', 10, 'Grilled Cheese Sandwich is a classic comfort food that is simple yet satisfying. Start by preheating a skillet or griddle over medium heat. Butter one side of each bread slice. Place one bread slice, butter side down, on the skillet. Top with cheese slices and another bread slice, butter side up. Cook until the bottom bread slice is golden brown and the cheese is melted, then flip and cook until the other side is golden brown. Serve hot and gooey for a deliciously cheesy treat.', 2, 6, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/grilledcheesesand.jpg?raw=true');
  
INSERT INTO recipes (name, ingredients, cooking_time, description, category_id, user_id, img)
VALUES ('Fish Tacos', 'White fish fillets (such as cod or tilapia), flour or corn tortillas, cabbage slaw, avocado, lime wedges, cilantro leaves, sour cream or Greek yogurt, hot sauce', 30, 'Fish Tacos are a light and flavorful dish that is perfect for a casual dinner or party. Start by seasoning the fish fillets with salt, pepper, and your favorite spices. Grill or pan-sear the fish until cooked through and flaky. Warm the tortillas on the grill or in a skillet until soft and pliable. To assemble the tacos, place a portion of cooked fish on each tortilla and top with cabbage slaw, sliced avocado, cilantro leaves, a squeeze of lime juice, and a dollop of sour cream or Greek yogurt. Serve with hot sauce on the side for an extra kick of flavor.', 2, 7, 'https://github.com/SinghALGO/recipe/blob/master/backend/public/images/fishtacos.jpg?raw=true');




